name: Auto Fix Code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  auto-fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black autopep8 pylint safety bandit
          pip install -r requirements.txt

      - name: Check security issues
        run: |
          safety check
          bandit -r .

      - name: Format code with Black
        run: |
          black app.py

      - name: Fix code with autopep8
        run: |
          autopep8 --in-place --recursive --aggressive app.py

      - name: Run Pylint
        run: |
          pylint --output-format=parseable --fail-under=8.0 app.py || echo "Warnings found but continuing"

      - name: Test basic functionality
        run: |
          python -c "
          import app
          import os
          assert os.path.exists('templates'), 'templates dir missing'
          assert os.path.exists('static'), 'static dir missing'
          "

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add app.py
          git diff --quiet && git diff --staged --quiet || (git commit -m "🤖 Auto-fix code formatting" && git push)